import constants
import oauth2
import urllib.parse as urlparse

# Passing our app keys and password
consumer = oauth2.Consumer(constants.c_key, constants.c_secret)
# Creating a client for our app to pass request
client = oauth2.Client(consumer)

# API call for request token(generated by Twitter API)
response, content = client.request(constants.request_token_url,'POST')

if response.status != 200:
    print("AN error occurred")

# content is query string
# Request token is generated when our application (e.g www.ourexample.com) first interacts with twitter.com when any user clicks the "Sign in with Twitter" option.
request_token = dict(urlparse.parse_qsl(content.decode('utf-8')))


# In Twitter.com when user clicks sign in, then twitter sends them back e.g. www.ourexample.com/auth and we get authorisaton token.
print("Please go to the below url:")
print("{}?oauth_token={}".format(constants.authorozation_url, request_token['oauth_token']))
oauth_verifier = input("what is pin ?")


# Then we send request_token+ authorisation_token to twitter and the we get access token back.
token = oauth2.Token(request_token['oauth_token'], request_token['oauth_token_secret'])
token.set_verifier(oauth_verifier)

# sending
client = oauth2.Client(consumer, token)
response, content = client.request(constants.access_token_url,'POST')
access_token = dict(urlparse.parse_qsl(content.decode('utf-8')))

print(access_token)






